version: "3.8"
services:
  ping_service:
    build: ./PingService
    # image: ping_service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    container_name: PingService
  receiver_service:
    build: ./ReceiverService
    # image: receiver_service
    container_name: ReceiverService